linters-settings:
  gosec:
    exclude-dir: cmd/opentelemetry
    exclude: "G104,G107"

linters:
  disable-all: true
  enable:
    - staticcheck
    - gosec
    - govet
  fast: false

issues:
  exclude-rules:
    - linters:
        - staticcheck
      path: pkg/queue/bounded_queue_test.go
#  - errcheck
#  - gofmt
#  - goimports
#  - golint
#  - gosec
#  - govet
#  - staticcheck


